In [2]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.ticker import NullFormatter
import pandas as pd
import numpy as np
import matplotlib.ticker as ticker
from sklearn import preprocessing
%matplotlib inline

In [3]:
#!pip install xlrd

In [4]:
# set up file names and read into dataframes
# accept input filenames from NodeJS server
ngo_filename = "5_NGO_database.xlsx"
hohk_programs_filename = "4_HandsOnProgram.xls"
volunteer_filename = "2_Dummy_Volunteer_Data.xls"
ngo_df = pd.read_excel(ngo_filename)
programs_df = pd.read_excel(hohk_programs_filename)
volunteers_df = pd.read_excel(volunteer_filename)

In [5]:
# drop irrelevant columns and reset index
colsToDropNgo = [0, 2, 3, 7, 8, 9, 10, 12, 15, 16, 17, 19, 21, 22, 24, 25, 26, 27, 30, 31,32,33, 34]
ngo_df.drop(ngo_df.columns[colsToDropNgo], axis=1, inplace=True)
ngo_df.index = np.arange(1,len(ngo_df)+1)
ngo_df.head()

,"Organization Name \n(Eng + Chinese, alphabetical order)",Focus Area\n,"Served Population Groups \n(e.g. Elderly, Children & Youth, Domestic Helper, EM, Family etc.)",Condition/Description of the Served Group,Location,No. of staff under the organization/centre,No. of beneficiary under the organization/centre,Work with us before?\n(Yes / No),Year of cooperation,"Corporate Program Wish List: \nPractical information \n(e.g. what kind of program/activity, what’s feasible, how big is the scale, prefered timing, any focus topic this year?)",Skill Based volunteers/Pro bono workshop needs,"Any facilities/activity rooms for program? (If Yes, please specify details - facilities type, room size…etc)"
1,Community Center A,"Others, please state in population served",Human right,NaN,Wan Chai Station,NaN,NaN,No,NaN,Event,NaN,NaN
2,Community Center B,NaN,NaN,Southern District residents,Wong Chuk Hang Station,50+,NaN,Yes,2018+2019,EM Tutorial Sessions,NaN,NaN
3,Community Center C,NaN,NaN,(Volunteer matching),Wan Chai Station,50+,NaN,Yes,2018,NaN,NaN,NaN
4,Enviromental Org,NaN,NaN,NaN,Mui Wo/None MTR can reach to,NaN,NaN,Yes,2018+2019,NaN,NaN,NaN
5,Community Center D,NaN,NaN,"visual impairement, blind and partially sighte...",Kai Tak station,NaN,NaN,Yes,2018+2019,NaN,NaN,NaN

In [6]:
# drop irrelevant columns and reset index
# also drop programs where status != active (cancelled or pending). can't do predictive modeling with time constraint. 
colsToDropProgs = [0, 5, 7, 8, 10, 11, 13, 14, 16, 17, 18]
programs_df.drop(programs_df.columns[colsToDropProgs], axis=1, inplace=True)
programs_df = programs_df[programs_df.Status == 'Active']
programs_df.index = np.arange(1,len(programs_df)+1)
programs_df.head()

,Status,Volunteer Opportunity: Total Hours Served- the hours of all occurences/service sessions under the volunteer service programs,Volunteer Opportunity: Populations Served,Volunteer Opportunity: Primary Impact Area,Volunteer Opportunity: Volunteer Opportunity Name,Location,Opportunity Coordinator,Maximum Attendance,Total Attended,Total Not Attended,Total Hours Served (for each occurrence/service session),Volunteer Opportunity: Record ID
1,Active,306.0,Environmental education; Integrated,Environmental Conservation ????,Serve-A-Thon: Soap Recycling 1:30 p.m. session...,Soap Cycling,HandsOn Hong Kong,16.0,8.0,2.0,16.0,a0N0I00001AFCUy
2,Active,306.0,Environmental education; Integrated,Environmental Conservation ????,Serve-A-Thon: Soap Recycling 1:30 p.m. session...,Soap Cycling,HandsOn Hong Kong,30.0,27.0,0.0,54.0,a0N0I00001AFCUy
3,Active,194.0,Integrated,Environmental Conservation ????,Serve-A-Thon: Soap Recycling 10 a.m. session (...,Soap Cycling,HandsOn Hong Kong,30.0,27.0,0.0,54.0,a0N0I00001AFCcJ
4,Active,194.0,Integrated,Environmental Conservation ????,Serve-A-Thon: Soap Recycling 10 a.m. session (...,Soap Cycling,HandsOn Hong Kong,30.0,28.0,0.0,56.0,a0N0I00001AFCcJ
5,Active,85.0,Hunger & homelessness,Hunger & Homelessness ????????????,Serve-A-Thon: Deliver Daily Necessities to Hom...,"ImpactHK, Sham Shui Po",HandsOn Hong Kong,3.0,7.0,0.0,14.0,a0N0I00001AFOJF

In [7]:
# drop columns and reset index
colsToDropVols = [0, 1, 5, 6, 7, 14]
volunteers_df.drop(volunteers_df.columns[colsToDropVols], axis=1, inplace=True)
volunteers_df.index = np.arange(1,len(volunteers_df)+1)
volunteers_df.head()

,Interests,Gender,Employment Status,Attendance Status,Connections: Hours Served,Contact: Hours Served (since account was created),Volunteer Opportunity: Volunteer Opportunity Name,Volunteer Opportunity: Managing Organization: Organization Name,Volunteer Opportunity: Type,Contact ID
1,NaN,Female,Other,Attended (and Hours Verified),1.50,25.24,Help Primary & Secondary School Kids of Hong K...,HandsOn Hong Kong ?????,Project,0030I00001KzFwb
2,NaN,Female,Other,Attended (and Hours Verified),1.50,25.24,Help Primary & Secondary School Kids of Hong K...,HandsOn Hong Kong ?????,Project,0030I00001KzFwb
3,NaN,Female,Other,Attended (and Hours Verified),1.50,25.24,Serve-A-Thon: Help Homework Group with Childre...,HandsOn Hong Kong ?????,Project,0030I00001KzFwb
4,Education and Empowerment for Children and You...,Female,Retired,Attended (and Hours Verified),2.00,13.76,Help Out at Hotmeal Service in Wan Chai,HandsOn Hong Kong ?????,Project,0030I00001LHaSZ
5,Education and Empowerment for Children and You...,Female,Retired,Attended (and Hours Verified),1.17,13.76,Help Ethnic Minority Primary Students with Sch...,HandsOn Hong Kong ?????,Project,0030I00001LHaSZ

In [8]:
# improving column-names' readability
ngo_df.columns = ['OrganizationName', 'FocusArea', 'ServedPopulationGroups', 'GroupsDescription', 'Location', 'NumOfStaff', 'NumOfBeneficiaries', 'WorkWithUsBefore', 'YearOfCooperation', 'WishList/PracticalInformation', 'SkillBasedVolunteerNeeds', 'AnyFacilitiesOrRooms']
programs_df.columns = ['Status', 'TotalHoursServedUnderProgram', 'PopulationsServed', 'PrimaryImpactArea', 'VolunteerOpportunityName', 'Location', 'OpportunityCoordinator', 'MaxAttendance', 'TotalAttended', 'TotalNotAttended', 'TotalHoursServedForEachOccurrence', 'OpportunityRecordID']
volunteers_df.columns = ['Interests', 'Gender', 'EmploymentStatus', 'AttendanceStatus', 'Connections:HoursServed', 'Contact:HoursServed', 'VolunteerOpportunityName', 'VolunteerOpportunityManagingOrgName', 'VolunteerOpportunityType', 'ContactID']

In [9]:
ngo_df.head()

,OrganizationName,FocusArea,ServedPopulationGroups,GroupsDescription,Location,NumOfStaff,NumOfBeneficiaries,WorkWithUsBefore,YearOfCooperation,WishList/PracticalInformation,SkillBasedVolunteerNeeds,AnyFacilitiesOrRooms
1,Community Center A,"Others, please state in population served",Human right,NaN,Wan Chai Station,NaN,NaN,No,NaN,Event,NaN,NaN
2,Community Center B,NaN,NaN,Southern District residents,Wong Chuk Hang Station,50+,NaN,Yes,2018+2019,EM Tutorial Sessions,NaN,NaN
3,Community Center C,NaN,NaN,(Volunteer matching),Wan Chai Station,50+,NaN,Yes,2018,NaN,NaN,NaN
4,Enviromental Org,NaN,NaN,NaN,Mui Wo/None MTR can reach to,NaN,NaN,Yes,2018+2019,NaN,NaN,NaN
5,Community Center D,NaN,NaN,"visual impairement, blind and partially sighte...",Kai Tak station,NaN,NaN,Yes,2018+2019,NaN,NaN,NaN

In [10]:
programs_df.head()

,Status,TotalHoursServedUnderProgram,PopulationsServed,PrimaryImpactArea,VolunteerOpportunityName,Location,OpportunityCoordinator,MaxAttendance,TotalAttended,TotalNotAttended,TotalHoursServedForEachOccurrence,OpportunityRecordID
1,Active,306.0,Environmental education; Integrated,Environmental Conservation ????,Serve-A-Thon: Soap Recycling 1:30 p.m. session...,Soap Cycling,HandsOn Hong Kong,16.0,8.0,2.0,16.0,a0N0I00001AFCUy
2,Active,306.0,Environmental education; Integrated,Environmental Conservation ????,Serve-A-Thon: Soap Recycling 1:30 p.m. session...,Soap Cycling,HandsOn Hong Kong,30.0,27.0,0.0,54.0,a0N0I00001AFCUy
3,Active,194.0,Integrated,Environmental Conservation ????,Serve-A-Thon: Soap Recycling 10 a.m. session (...,Soap Cycling,HandsOn Hong Kong,30.0,27.0,0.0,54.0,a0N0I00001AFCcJ
4,Active,194.0,Integrated,Environmental Conservation ????,Serve-A-Thon: Soap Recycling 10 a.m. session (...,Soap Cycling,HandsOn Hong Kong,30.0,28.0,0.0,56.0,a0N0I00001AFCcJ
5,Active,85.0,Hunger & homelessness,Hunger & Homelessness ????????????,Serve-A-Thon: Deliver Daily Necessities to Hom...,"ImpactHK, Sham Shui Po",HandsOn Hong Kong,3.0,7.0,0.0,14.0,a0N0I00001AFOJF

In [11]:
volunteers_df.head()

,Interests,Gender,EmploymentStatus,AttendanceStatus,Connections:HoursServed,Contact:HoursServed,VolunteerOpportunityName,VolunteerOpportunityManagingOrgName,VolunteerOpportunityType,ContactID
1,NaN,Female,Other,Attended (and Hours Verified),1.50,25.24,Help Primary & Secondary School Kids of Hong K...,HandsOn Hong Kong ?????,Project,0030I00001KzFwb
2,NaN,Female,Other,Attended (and Hours Verified),1.50,25.24,Help Primary & Secondary School Kids of Hong K...,HandsOn Hong Kong ?????,Project,0030I00001KzFwb
3,NaN,Female,Other,Attended (and Hours Verified),1.50,25.24,Serve-A-Thon: Help Homework Group with Childre...,HandsOn Hong Kong ?????,Project,0030I00001KzFwb
4,Education and Empowerment for Children and You...,Female,Retired,Attended (and Hours Verified),2.00,13.76,Help Out at Hotmeal Service in Wan Chai,HandsOn Hong Kong ?????,Project,0030I00001LHaSZ
5,Education and Empowerment for Children and You...,Female,Retired,Attended (and Hours Verified),1.17,13.76,Help Ethnic Minority Primary Students with Sch...,HandsOn Hong Kong ?????,Project,0030I00001LHaSZ

In [12]:
# volunteers by age
femaleCount = volunteers_df['Gender'].value_counts()['Female']
maleCount = volunteers_df['Gender'].value_counts()['Male']
genderGraph = [[femaleCount, maleCount], ["Female", "Male"]]
genderGraph

[[84, 15], ['Female', 'Male']]

In [32]:
programs_df['EventType'] = programs_df['VolunteerOpportunityName']

In [33]:
programs_df.head()

,Status,TotalHoursServedUnderProgram,PopulationsServed,PrimaryImpactArea,VolunteerOpportunityName,Location,OpportunityCoordinator,MaxAttendance,TotalAttended,TotalNotAttended,TotalHoursServedForEachOccurrence,OpportunityRecordID,EventType
1,Active,306.0,Environmental education; Integrated,Environmental Conservation ????,Serve-A-Thon: Soap Recycling 1:30 p.m. session...,Soap Cycling,HandsOn Hong Kong,16.0,8.0,2.0,16.0,a0N0I00001AFCUy,Serve-A-Thon: Soap Recycling 1:30 p.m. session...
2,Active,306.0,Environmental education; Integrated,Environmental Conservation ????,Serve-A-Thon: Soap Recycling 1:30 p.m. session...,Soap Cycling,HandsOn Hong Kong,30.0,27.0,0.0,54.0,a0N0I00001AFCUy,Serve-A-Thon: Soap Recycling 1:30 p.m. session...
3,Active,194.0,Integrated,Environmental Conservation ????,Serve-A-Thon: Soap Recycling 10 a.m. session (...,Soap Cycling,HandsOn Hong Kong,30.0,27.0,0.0,54.0,a0N0I00001AFCcJ,Serve-A-Thon: Soap Recycling 10 a.m. session (...
4,Active,194.0,Integrated,Environmental Conservation ????,Serve-A-Thon: Soap Recycling 10 a.m. session (...,Soap Cycling,HandsOn Hong Kong,30.0,28.0,0.0,56.0,a0N0I00001AFCcJ,Serve-A-Thon: Soap Recycling 10 a.m. session (...
5,Active,85.0,Hunger & homelessness,Hunger & Homelessness ????????????,Serve-A-Thon: Deliver Daily Necessities to Hom...,"ImpactHK, Sham Shui Po",HandsOn Hong Kong,3.0,7.0,0.0,14.0,a0N0I00001AFOJF,Serve-A-Thon: Deliver Daily Necessities to Hom...

In [43]:
#programs_df.EventType = programs_df.EventType.split(':')[0]
for i in range(1, len(programs_df.EventType)+1):
    programs_df.EventType[i] = programs_df.EventType[i].split(':')[0]
    #programs_df.EventType[
    #print(i)

c:\users\bevan\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [44]:
programs_df.EventType

1                                           Serve-A-Thon
2                                           Serve-A-Thon
3                                           Serve-A-Thon
4                                           Serve-A-Thon
5                                           Serve-A-Thon
                             ...
399                                    Youth Opportunity
400                                    Youth Opportunity
401                                    Youth Opportunity
402                                    Youth Opportunity
403    Help at Play Group with Students with Intellec...
Name: EventType, Length: 403, dtype: object

In [46]:
programs_df.EventType.value_counts(ascending=False)

Youth Opportunity                                                                143
Serve-A-Thon                                                                      59
Youth Opportunities                                                               47
COVID-19 Relief                                                                   28
Phone call support to 1 elderly individual [PRE-TRAINED VOLUNTEERS ONLY]          26
Family Opportunity                                                                23
Youth opportunity                                                                 19
Serve-a-thon                                                                      15
Be a Sports Class Assistant for People with Special Needs                         12
Help Hearing-Impaired Children with Schoolwork in To Kwa Wan                       6
Help Ethnic Minority Children with Homework in Jordan                              4
Help and Be the Storyteller at Story Telling Corner with Children                  2
HandsOn Care Pack Delivery Volunteer Leader Information and Training Session       2
2020 VF Purpose Day - Wetland Habitat Preservation                                 2
Training session                                                                   2
Help Students with Intellectual Disabilities at Job-related Online Training        2
Testing SBV                                                                        1
Test_VO                                                                            1
Help at Play Group with Students with Intellectual Disabilities                    1
Help at Play Group with Students with Physical Disabilities                        1
Online training session                                                            1
LGT - (English) Phone call support to elderly [PRE-TRAINED VOLUNTEERS ONLY]        1
Youth Empowered                                                                    1
2020 VF Purpose Week Pilot Program - Creating Educational Videos for Students      1
LGT - (Cantonese) Phone call support to elderly [PRE-TRAINED VOLUNTEERS ONLY]      1
Distributing Hygiene Kits to Street Cleaners                                       1
2020 VF Purpose Week - testing                                                     1
Name: EventType, dtype: int64

In [73]:
programs_df.head()

,Status,TotalHoursServedUnderProgram,PopulationsServed,PrimaryImpactArea,VolunteerOpportunityName,Location,OpportunityCoordinator,MaxAttendance,TotalAttended,TotalNotAttended,TotalHoursServedForEachOccurrence,OpportunityRecordID,EventType
1,Active,306.0,Environmental education; Integrated,Environmental Conservation ????,Serve-A-Thon: Soap Recycling 1:30 p.m. session...,Soap Cycling,HandsOn Hong Kong,16.0,8.0,2.0,16.0,a0N0I00001AFCUy,Serve-A-Thon
2,Active,306.0,Environmental education; Integrated,Environmental Conservation ????,Serve-A-Thon: Soap Recycling 1:30 p.m. session...,Soap Cycling,HandsOn Hong Kong,30.0,27.0,0.0,54.0,a0N0I00001AFCUy,Serve-A-Thon
3,Active,194.0,Integrated,Environmental Conservation ????,Serve-A-Thon: Soap Recycling 10 a.m. session (...,Soap Cycling,HandsOn Hong Kong,30.0,27.0,0.0,54.0,a0N0I00001AFCcJ,Serve-A-Thon
4,Active,194.0,Integrated,Environmental Conservation ????,Serve-A-Thon: Soap Recycling 10 a.m. session (...,Soap Cycling,HandsOn Hong Kong,30.0,28.0,0.0,56.0,a0N0I00001AFCcJ,Serve-A-Thon
5,Active,85.0,Hunger & homelessness,Hunger & Homelessness ????????????,Serve-A-Thon: Deliver Daily Necessities to Hom...,"ImpactHK, Sham Shui Po",HandsOn Hong Kong,3.0,7.0,0.0,14.0,a0N0I00001AFOJF,Serve-A-Thon

In [75]:
participationRate = programs_df.groupby(['EventType'])['MaxAttendance','TotalAttended'].count().to_frame()

c:\users\bevan\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  """Entry point for launching an IPython kernel.

AttributeError: 'DataFrame' object has no attribute 'to_frame'

In [71]:
#pd.DataFrame(participationRate.size().reset_index())

                                            EventType    0
0   2020 VF Purpose Day - Wetland Habitat Preserva...    2
1                      2020 VF Purpose Week - testing    1
2   2020 VF Purpose Week Pilot Program - Creating ...    1
3   Be a Sports Class Assistant for People with Sp...   12
4                                     COVID-19 Relief   28
5        Distributing Hygiene Kits to Street Cleaners    1
6                                  Family Opportunity   23
7   HandsOn Care Pack Delivery Volunteer Leader In...    2
8   Help Ethnic Minority Children with Homework in...    4
9   Help Hearing-Impaired Children with Schoolwork...    6
10  Help Students with Intellectual Disabilities a...    2
11  Help and Be the Storyteller at Story Telling C...    2
12  Help at Play Group with Students with Intellec...    1
13  Help at Play Group with Students with Physical...    1
14  LGT - (Cantonese) Phone call support to elderl...    1
15  LGT - (English) Phone call support to elderly ...    1
16                            Online training session    1
17  Phone call support to 1 elderly individual [PR...   26
18                                       Serve-A-Thon   59
19                                       Serve-a-thon   15
20                                            Test_VO    1
21                                        Testing SBV    1
22                                   Training session    2
23                                    Youth Empowered    1
24                                Youth Opportunities   47
25                                  Youth Opportunity  143
26                                  Youth opportunity   19